name: test-vim9

on:
  push:
    branches: [vim9]
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!.gitignore'
      - '!LICENSE'
      - '!doc/**'
      - '.github/**'
      - 'autoload/**'
      - 'tests/**'
      - 'examples/**'

  pull_request:
    branches: [vim9]

jobs:
  test-on-Ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build latest Vim
        run: |
          git clone https://github.com/vim/vim.git --depth=1 -j 4
          cd vim
          mkdir $HOME/local
          ./configure --prefix=$HOME/local
          make -j4
          make install

      - name: Test
        run: $HOME/local/bin/vim -S tests/test.vim ; cat test.log
