name: test

on:
  push:
    branches: [main]
    tags:
      - v*.*.*

  pull_request:
    branches: [main]

jobs:
  test-on-Ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build latest Vim
        run: |
          git clone https://github.com/vim/vim.git --depth=1 -j 4
          cd vim
          mkdir $HOME/local
          ./configure --prefix=$HOME/local
          make -j4
          make install

      - name: Test
        run: $HOME/local/bin/vim -S tests/test.vim ; echo test_result.log
